version: '2'

services:
  drone-server:
    image: ${DRONE_DOCKER_IMAGE}
    ports:
      - ${DRONE_PORT}:8000
    volumes:
      - "./drone:/var/lib/drone"
    privileged: true
    restart: always
    environment:
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_OPEN=${DRONE_OPEN}
      - DRONE_GITHUB=${DRONE_GITHUB}
      - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}
      - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}
      - DRONE_GITHUB_SCOPE=${DRONE_GITHUB_SCOPE}
      - DRONE_GITHUB_SKIP_VERIFY=${DRONE_GITHUB_SKIP_VERIFY}      
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_ADMIN=${DRONE_ADMIN}
      - DRONE_DEBUG=${DRONE_DEBUG}

  drone-agent-01:
    image: ${DRONE_DOCKER_IMAGE}
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_DEBUG=${DRONE_DEBUG}

  drone-agent-02:
    image: ${DRONE_DOCKER_IMAGE}
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_DEBUG=${DRONE_DEBUG}

  drone-agent-03:
    image: ${DRONE_DOCKER_IMAGE}
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_DEBUG=${DRONE_DEBUG}
